# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170209_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_url',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer_url',
            name='paid_url',
        ),
        migrations.DeleteModel(
            name='Customer_URL',
        ),
    ]
