# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0005_auto_20170209_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paid_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.Shortener_URL')),
            ],
        ),
    ]
