# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_customer_url_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_url',
            name='clicks',
        ),
    ]
